import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 border ">
          <nav className="flex gap-4">
            <Link href={"/"} className="mr-5">
              Home
            </Link>
            <Link href={"/products"} className="ml-5">
              Products{" "}
            </Link>
            <Link href={"/profile"}> Profile</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
